In [29]:
from shareplum import Site
from shareplum import Office365
import pandas as pd
from pandas import DataFrame

In [26]:
server_url = "https://townsendpolymer.sharepoint.com/"
site_url = server_url + "sites/TownsendPortal/"
authcookie = Office365(server_url, username='ltao@townsendsolutions.com', password='2800Tl@@').GetCookies()
site = Site(site_url, authcookie=authcookie)
sp_list = site.List('Bioplastics Capacity')
data = sp_list.GetListItems('All Items')
DataFrame(data)

,ID,Status,Region,Country,ProvinceState,City,Producer,Group,% Resin Holding,Material type,...,Jan 1 2010 Capacity (kt),Jan 1 2011 Capacity (kt),Jan 1 2012 Capacity (kt),Jan 1 2013 Capacity (kt),Jan 1 2014 Capacity (kt),Jan 1 2015 Capacity (kt),Feedstock,Start-up Year,Process,JV Partner
0,1,Active,Asia Pacific,South Korea,Kyungki,Pyongtack,AU,AU,1.0,Bio PE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Active,Asia Pacific,South Korea,Kyungki,Pyongtack,AU,AU,1.0,Bio PP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Active,Asia Pacific,South Korea,Incheon,Incheon,ECOMASS,ECOMASS,1.0,Bio PE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Active,Asia Pacific,South Korea,Kyungki,Buchen,BMP,BMP,1.0,Bio PE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Active,Asia Pacific,South Korea,Junlabukdo,Junju,Huvis,Huvis,1.0,Bio PET,...,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,Active,Asia Pacific,Japan,Hyogo,Takasago,Kaneka,Kaneka,1.0,PHBH,...,NaN,NaN,NaN,NaN,NaN,NaN,Plant oil,2011.0,Fermentation,NaN
116,117,Active,Asia Pacific,Japan,Hiroshima,Ohtake,Daicel Corporation,Daicel Corporation,1.0,PCL,...,NaN,NaN,NaN,NaN,NaN,NaN,Cyclohexanone,NaN,NaN,NaN
117,118,Active,Asia Pacific,Japan,Fukushima,Iwaki,Kureha Corporation,Kureha Corporation,1.0,PGA,...,NaN,NaN,NaN,NaN,NaN,NaN,Glycolic acid,NaN,NaN,NaN
118,119,Active,Asia Pacific,Japan,Yamaguchi,Iwakun,Toyobo Co. Ltd,Toyobo Co. Ltd,1.0,PLA,...,NaN,NaN,NaN,NaN,NaN,NaN,Lactide,NaN,NaN,NaN
119,120,New,Africa,South Africa,NaN,NaN,CSIR,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,biomass feed-stocks,NaN,NaN,UNIDO/ JAPAN

In [27]:
site.AddList('test list', description='Great List!', template_id='Custom List')

ShareplumRequestError: Shareplum HTTP Post Failed : 500 Server Error: Internal Server Error for url: https://townsendpolymer.sharepoint.com/sites/TownsendPortal//_vti_bin/lists.asmx

In [32]:
my_data = data=[{'Title': 'First Row!'},
                {'Title': 'Another One!'}]

    MAX  Hero  Ukmow  Micky  Xiah
0  1988  1986   1986   1986  1986
1     1     4      7     10    13
2     2     5      8     11    14
3     3     6      9     12    15

In [91]:
new_list = site.List('test list')
my_data = pd.read_excel('TVXQ.xlsx', index=0, index_col=False)  
data_list = [my_data.to_dict()]
data_list

[{'MAX': {0: 1988, 1: 1, 2: 2, 3: 3},
  'Hero': {0: 1986, 1: 4, 2: 5, 3: 6},
  'Ukmow': {0: 1986, 1: 7, 2: 8, 3: 9},
  'Micky': {0: 1986, 1: 10, 2: 11, 3: 12},
  'Xiah': {0: 1986, 1: 13, 2: 14, 3: 15}}]

In [92]:

new_list.UpdateListItems(data=data_list, kind='New')

Exception: MAX not a column in current List.